### ISSUE TITLE
Cache node_modules on build

### ISSUE THREAD

**Issue by bensalilijames** [mars/heroku-nextjs-build#4]
I'm not too familiar with Heroku buildpacks but it seems to me that the `node_modules` for the app are being saved into `nextjs/node_modules`, which doesn't restore itself upon a new deploy.

This then results in having to download all the `node_modules` again on every deploy, regardless of whether they've changed or not. I'm thus looking at very long times between `git push` and the start of the actual build.

Is there a quick fix/win here to improve iteration times?

Thanks! 😃

**Comment by mars** [comment]
If you follow the [Production deployment docs](https://github.com/mars/heroku-nextjs#production-deployment) on the main example repo, you'll see that the cache directory config should be merged into `package.json`:

  ```json
  {
    "scripts": {
      "start": "next start -p $PORT",
      "heroku-postbuild": "heroku-nextjs-build"
    },
    "engines": {
      "node": "6.9.x"
    },
    "cacheDirectories": [
      "nextjs/node_modules"
    ]
  }
  ```

Also worth noting, is that the build process contained in this repo/module also [sets up the cache directory after the build](https://github.com/mars/heroku-nextjs-build/blob/master/bin/heroku-nextjs-build#L56), after the Next app has been relocated to `/app/nextjs`.

Both of these cache directory settings are required to restore the cache before build and save the cache after build.

**Comment by bensalilijames** [comment]
Oops - completely my bad for not reading. Thanks!
